server:
   port: 80
   servlet:
      context-path: /api
spring:
   datasource:
      first:
         jdbc-url: jdbc:mysql://192.168.85.129:3306/tsdb?useSSL=false
         username: mysql
         password: mysql
         driver-class-name: com.mysql.cj.jdbc.Driver
      second:
         jdbc-url: jdbc:mysql://192.168.85.129:3306/tsdb2?useSSL=false
         username: mysql
         password: mysql
         driver-class-name: com.mysql.cj.jdbc.Driver
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 100MB
   rabbitmq:
      host: 192.168.85.129
      port: 5672
      username: admin
      password: admin
   redis:
      database: 0
      cluster:
         nodes:
         - 192.168.85.129:7001
         - 192.168.85.129:7002
         - 192.168.85.129:7003
         - 192.168.85.129:7004
         - 192.168.85.129:7005
         - 192.168.85.129:7006
    lettuce: null
#password: 123456
      pool: null
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
 #连接池最大连接数（使用负值表示没有限制） #连接池最大连接数（使用负值表示没有限制） #连接池最大连接数（使用负值表示没有限制） #连接池最大连接数（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.example.demo.model
task:
   print: 0 0/1 * * * ?
netty:
   port: 7000
   url: 172.18.73.135
logging:
   level:
      com:
         example:
#showSql
            demo: debug
biz:
   user:
      topic: item_queue
